### ISSUE TITLE
Change character returned by battery widget

### ISSUE THREAD

**Issue by dudelson** [Mic92/vicious#36]
While debugging some code I wrote that interacts with the vicious battery
widget, I found that when the battery is discharging, the status character returned by
the battery widget is not a hyphen ('-', U+002D), but rather the mathematical
minus operator character ('−', U+2212). The assumption on my part that this was
a hyphen lead to a rather insidious bug. This is especially confusing because
the charging status character is an actual plus sign ('+', U+002B). I think in this case it's better to
conform to developers' expectations in order to make working with the vicious
library easier, and since I think that probably most people would have made the
same mistake I did, I propose that the discharing status character returned by
the battery widget be changed to an actual hyphen.

**Comment by Mic92** [comment]
Do want to make a pull request?
