### ISSUE TITLE
Setting the font.

### ISSUE THREAD

**Issue by kierun** [Mic92/vicious#38]
How can you set the font that the widgets use?

**Comment by mutlusun** [comment]
Hello kierun,

indeed there is no example in the readme file and not on the official awesome page. I assume this information got lost as they retired their old wiki (this question is not related to vicious but to awesome).

Here is an example:
```lua
mydate = wibox.widget.textbox()
vicious.register(mydate, vicious.widgets.date, "<span color=\"#ffffff\">%b %d, %R</span>", 61)
myvolume = wibox.widget.textbox()
vicious.register(myvolume, vicious.widgets.volume, "<span font_size='larger'>$3</span> $1%", 269, "vol")
``` 

In the span block you can use common html attributes. I hope this answers your question.
