### ISSUE TITLE
Compatibility with Awesome 4.0?

### ISSUE THREAD

**Issue by franck-talbart** [Mic92/vicious#39]
Dear All,

I am trying to use Vicious in Awesome v4.0 (Debian 9).
I would lke to display widgets to show the battery status, cpu, memory, .... like I was doing in Awesome 3.x.
Unfortunately, that does not seem to work, as nothing is displayed (but no crash either).

Is vicious compatible with Awesome 4.x ? Am I missing something ?
Thanks a lot for your help!

    -- Battery
    battwidget = wibox.widget({ type = "textbox" })
    vicious.register(battwidget, vicious.widgets.bat, 'Batt: $2% / ', 61, 'BAT1')

    -- CPU
    cpuwidget = wibox.widget({ type = "textbox" })
    vicious.register(cpuwidget, vicious.widgets.cpu, 'CPU: $1% / ')
    -- Mem
    memwidget = wibox.widget({ type = "textbox" })
    vicious.register(memwidget, vicious.widgets.mem, 'Mem: $1% ($2MB/$3MB) / ', 13)

   [...]

    -- Add widgets to the wibox
    s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            layout = wibox.layout.fixed.horizontal,
            mylauncher,
            s.mytaglist,
            s.mypromptbox,
        },
        s.mytasklist, -- Middle widget
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            mykeyboardlayout,
            wibox.widget.systray(),
            mytextclock,
            cpuwidget,
            memwidget,
            battwidget,
            s.mylayoutbox,
        },
    }

**Comment by Mic92** [comment]
It is compatible with both awesome 3 and awesome 4. (I run awesome 4.1). However you might have to look at the `mywibox` code, which is out of scope of `vicious`. The API there has changed a little also I think the old API was still preserved for compatibility. Here is what I use: https://github.com/Mic92/awesome-dotfiles/blob/master/rc.lua#L659

**Comment by franck-talbart** [comment]
Thanks a lot for your help!
Actually, the following line:
    wibox.widget({ type = "textbox" })
must be replaced by
    wibox.widget.textbox()
