### ISSUE TITLE
Volume Widget shellquote issue

### ISSUE THREAD

**Issue by bhartshorn** [Mic92/vicious#41]
When I pass "Master -D pulse" as wargs to vicious.widgets.volume, the helpers.shellquote function makes the final amixer command `amixer -M get 'Master -D pulse'`. This command line just returns 
`amixer: Unable to find simple control 'Master '-D pulse'',0`

I noticed in the commit history that the shellquote helper function was added to the volume widget in 2014. Am I missing something obvious about how to configure this widget, or is this a long-standing bug?

**Comment by Mic92** [comment]
At the moment we only support adding a single argument to this widget.
