### ISSUE TITLE
Error when upgrading to v2.3.0

### ISSUE THREAD

**Issue by KevinSeroux** [Mic92/vicious#48]
Hello!

This morning I upgraded vicious from v2.2.0 to v2.3.0 and it seems that something is broken.
I use ArchLinux and downgrading the package to v2.2.0 make it to work again.

> error while running function!
> stack traceback:
>     /usr/share/lua/5.3/vicious/init.lua:85: in upvalue 'update'
>     /usr/share/lua/5.3/vicious/init.lua:173: in field 'update'
>     /usr/share/lua/5.3/vicious/init.lua:149: in upvalue 'regregister'
>     /usr/share/lua/5.3/vicious/init.lua:182: in function 'vicious.register'
>     /home/user/.config/awesome/rc.lua:157: in main chunk
> error: /usr/share/lua/5.3/vicious/init.lua:85: attempt to index a function value (field 'wtype') 

```lua
cputempwidget = wibox.widget.textbox()
vicious.register(cputempwidget,
function()
    local f = io.popen("sensors | grep 'Package id 0:' | awk '{print $4}'")
    local output = f:read("*all"):gsub('\n', '')
    f:close()
    return " [ CPU <span foreground='white'>" .. output .. "</span> ]"
end)
```

Thanks in advance. :)

**Comment by Mic92** [comment]
a widget must be a table, not a function.
The following (untested) code might work:

```lua
cputempwidget = wibox.widget.textbox()

local cputemp = setmetatable({}, {
     __call = function()
         local f = io.popen("sensors | grep 'Package id 0:' | awk '{print $4}'")
         local output = f:read("*all"):gsub('\n', '')
         f:close()
         return " [ CPU <span foreground='white'>" .. output .. "</span> ]"
    end
})
vicious.register(cputempwidget, cputemp)
```

**Comment by KevinSeroux** [comment]
Thanks a lot. It works. :)

But shouldn't the README be updated to inform users?

> For them Vicious kept the old Wicked functionality, possibility to register their own functions as widget types. By providing them as the second argument to vicious.register. Your function can accept "format" and "warg" arguments, just like workers.'

Actually I find it weird that I'm the only one having this issue, I thought that registering a function was the standard way to create widgets. My bad.

**Comment by terramorpher** [comment]
Same here. The following widget worked without any problems:

`-- Create a memory widget
memwidget = wibox.widget.textbox()
vicious.cache(vicious.widgets.mem)
vicious.register(memwidget, vicious.widgets.mem,                                                                                                                                                            
function(widget,args)
memp_tot = string.format("%02d",args[1])
t = 
'<span color="#7E8AA2">  mem</span> '..memp_tot..'<span color="#B1D631">%</span>'
return t
end
, 7)`

Now, the value disappeared.

**Comment by Mic92** [comment]
Probably compatibility can be restored by checking if it is a function.

**Comment by Mic92** [comment]
I added to 050dbd30d3fbe4e1835cbcba8c605c943cb3e138 to restore the old behavior. Can you test it?

**Comment by terramorpher** [comment]
Thank you for the update - unfortunately it didn't work. But in the meantime I found out, that disabling the `vicious.cache()` for eacht widget bring the old behavior back.

**Comment by Mic92** [comment]
@terramorpher your problem is unrelated to the issue to the problem pointed out by @KevinSeroux 
You are not using a your own widget function, but a format function.
