### ISSUE TITLE
fs feature request - optionally specify which explicit filesystem to look at

### ISSUE THREAD

**Issue by csrl** [Mic92/vicious#50]
Currently the fs widget takes a truthy 'wargs' option to enable returning remote filesystems instead of just local.

I'd like to have that change, so that wargs takes an optional array of filesystems to look at.

eg:  {'/', '/tmp', '/media/user1/thumbdrive'}

Obviously just returning all file system, and filtering the results, as we have it today is usable, but limiting what is returned has its use as well.

A backwards compatible approach would be as simple as:

```patch
diff --git a/widgets/fs_all.lua b/widgets/fs_all.lua
index b577431..4ae46ae 100644
--- a/widgets/fs_all.lua
+++ b/widgets/fs_all.lua
@@ -27,6 +27,10 @@ local function worker(format, warg)
     if not warg then
       -- List only local filesystems by default
       cmd = cmd .. " -l"
+    elseif type(warg) == "table" then
+      for i = 1, #warg do
+        cmd = cmd .. " " .. helpers.shellquote(warg[i])
+      end
     end
 
     local fs_info = {} -- Get data from df
```

**Comment by Mic92** [comment]
What is the advantage?

**Comment by csrl** [comment]
Generally, I find it nicer to control what is produced, vs filter the output.  But otherwise, it provides a minor readability improvement and simplification of the calling code when attempting reuse of a generic format function. eg.

`vicious.register(fsrootwidget, vicious.widgets.fs, fsformat, 17, {"/"})`
`vicious.register(fstmpwidget, vicious.widgets.fs, fsformat, 18, {"/tmp"})`

Without this, it looks like:

`vicious.register(fsrootwidget, vicious.widgets.fs, makefsformat("/"), 17)`
`vicious.register(fstmpwidget, vicious.widgets.fs, makefsformat("/tmp"), 18)`

And the code associated with makefsformat is a little uglier in generating a format function that acts on the appropriate entries.

If there is a reason not to provide this, no big loss.

**Comment by Mic92** [comment]
For sake of simplicity I would not implement this functionality.
