### ISSUE TITLE
FreeBSD support for memory widget w/patch

### ISSUE THREAD

**Issue by dkrand** [Mic92/vicious#54]
I couldn't get the mem.lua widget to easily work well on FreeBSD with /compat/linux/proc/meminfo via the linprocfs filesystem. The memory stats seemed to be wildly wrong. So I leveraged your sysctl helper and hacked together a mem_freebsd.lua module. It doesn't support buffer memory (since I didn't find source of that data) but otherwise does everything else that mem.lua does.

I couldn't find a nice and easy way to get summary swap information, but meminfo via linprocfs does that, so I just used that.

**Comment by dkrand** [comment]
[mem_freebsd.lua.txt](https://github.com/Mic92/vicious/files/1793765/mem_freebsd.lua.txt)

**Comment by Mic92** [comment]
cc @mutlusun

**Comment by mutlusun** [comment]
Hello,
I'm sorry for the late reply. As @psycorama pointed out, the current implementation for FreeBSD uses sysctl as provider. So there is no need to use the compat layer. But I tested this widget again and I found several errors in the reported numbers. For example the first argument doesn't give the used memory, it gives the free memory. I will provide a pull request.

**Comment by psycorama** [comment]
Hy again.

I do agree with @mutlusun pointing out bugs, but i have to disagree with his assessment for the first returned argument. 
I'm a bit under the weather at the moment, but i will provide another pull request within the next days.

So, maybe hold back with merging for a bit?

**Comment by dkrand** [comment]
On 03/09/18 05:57, Andreas Geisenhainer wrote:
> What's wrong with the current implementation for FreeBSD?

Blush!  Mainly the fact that I didn't look at the most recent version of 
Viscious.   Sorry about that. I had 2.1.3, not the master branch. Never even 
looked at the master branch I'm embarrassed to say.

But, there are a few problems with it though.  Swap space usage isn't 
calculated correctly. It uses vm.swapin out of the vm.stats table, and the 
description of that OID is:

% sysctl -d vm.stats.vm.v_swapin
vm.stats.vm.v_swapin: Swap pager pageins

Which is not the amount of swap space in use. I could not find a sysctl that 
reported swap space in use. There is the system call kvm_swapinfo(3) and the 
swapinfo(8) command both of which seem to do the right thing, but I didn't 
want to figure out how to call kvm_swapinfo(3) from Lua. Nor did I want the 
hassle of having to parsing the output of swapinfo and summing each of the 
rows. (With multiple swap devices, which admittedly is rare these days, 
swapinfo produces multiple lines.)

Just as I was typing this I had these values:

vm.swap_total:         17,179,869,184
vm.stats.vm.v_swapin: 121,058,209,792

(white space and commas added for clarity)

While top reports: Swap: 16G Total, 251M Used, 16G Free, 1% Inuse

And swapinfo -k:
Device          1K-blocks     Used    Avail Capacity
/dev/gpt/swap0   16777216   257080 16520136     2%


On the memory front, using gkrellm as my benchmark (and there are perfectly 
valid comments that gkrellm isn't a good benchmark) "free" memory is 
vm.v_free_count plus vm.v_inactive_count.  Which is why I used that.

Sorry for missing the great work on providing additional FreeBSD support and 
the compat layer also.

**Comment by mutlusun** [comment]
I started a lot of processes on my laptop and can confirm that `vm.stats.vm.v_swapin` does not correspond to the `swapinfo` information.
@psycorama : Do you have any idea, how to correctly read swap information from sysctl?

**Comment by psycorama** [comment]
No, sorry. I only got one system with swap, and it's a headless root-server.
The information I got from ```swapinfo``` and ```top``` does not line up a hundred percent, too
